version: '3.7'

services:
  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e
      - MYSQL_DATABASE=UsersData
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1q2w3e
    volumes:
      - /data/mysql
  tema2-rest-app:
    image: tema2-rest-app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 8087:8080
    volumes:
      - /data/tema2-app
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1q2w3e
      - DATABASE_NAME=UsersData
      - DATABASE_PORT=3306