version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e
      - MYSQL_DATABASE=UsersData
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1q2w3e
    volumes:
      - /data/mysql
  tema2-rest-app:
    image: tema2-rest-app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8087:8080
    volumes:
      - /data/tema2-app
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1q2w3e
      - DATABASE_NAME=UsersData
      - DATABASE_PORT=3306